language: node_js
node_js: node
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: fdb9b9415916c45bd717855d7958e0a6bc7e55f0
  keep-history: true
  local-dir: ./dist
  on:
    branch: master