language: node_js
node_js: node
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 552cab6c7e33bd839cd243caa771150fb2fc2806
  keep-history: true
  local-dir: ./dist
  on:
    branch: master